### GET request to example server

###Get all dealerships with params
GET http://localhost:8080/webapi/dealerships?phrase=foo









###Get all cars
GET http://localhost:8080/webapi/cars

###Get car by id
GET http://localhost:8080/webapi/cars/1

###Get cars from dealership
GET http://localhost:8080/webapi/dealership/1/car

### create new car
POST http://localhost:8080/webapi/cars
Content-Type: application/json

{

  "model": "Niemampojeciajuz",
  "price": 100000.0,
  "brandId": 1
}





###Get all dealerships wit params
GET http://localhost:8080/webapi/dealerships?phrase=abc
custom-header: custom-value
Cookie: some-cookie=some-value
###
GET http://localhost:8080/webapi/dealerships/1
Accept: application/xml
###
GET http://localhost:8080/webapi/dealerships/5
###
GET http://localhost:8080/webapi/dealerships
###
GET http://localhost:8080/webapi/cars/1/dealerships
### create new dealership
POST http://localhost:8080/webapi/dealerships
Content-Type: application/json

{
  "name": "New dealership",
  "logo": "https://as2.ftcdn.net/v2/jpg/17/14/42/95/1000_F_1714429500_8BVcMCHGxyDQItv1UGL3VvjP9y2t714Y.jpg"
}
### create new dealership with error
POST http://localhost:8080/webapi/dealerships
Content-Type: application/json
Accept-Language: it

{
  "name": "",
  "logo": "https://as2.ftcdn.net/v2/jpg/17/14/42/95/1000_F_1714429500_8BVcMCHGxyDQItv1UGL3VvjP9y2t714Y.jpg"
}
### create new with doubled name
POST http://localhost:8080/webapi/dealerships
Content-Type: application/json
Accept-Language: it

{
  "name": "vcentrum",
  "logo": "https://as2.ftcdn.net/v2/jpg/17/14/42/95/1000_F_1714429500_8BVcMCHGxyDQItv1UGL3VvjP9y2t714Y.jpg"
}




### create new car
POST http://localhost:8080/webapi/cars
Content-Type: application/json

{
  "model": "458",
  "brandId": 1,
  "price": 10305.0
}